server:
  port: 8087

spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/kabba_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    sqlserver:
      url: jdbc:sqlserver://192.168.1.92:1433;DatabaseName=erm
      username: sa
      password: 123
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        initial-size: 5
        min-idle: 15
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        druid.filters: stat,wall,log4j

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.kabba.transform.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

workerid: 1
datacenterid: 1